using QKNWZ1_HFT_2021221.Models;

[assembly: System.CLSCompliant(false)]
namespace QKNWZ1_HFT_2021221.Test
{
	/// <summary>
	/// Contains methods that return an array of source data for testing.
	/// </summary>
	public static class TestDataSource
	{
		/// <summary>Returns an array of <see cref="ExpertGroup"/> objects.</summary>
		/// <returns>An array of <see cref="ExpertGroup"/> objects.</returns>
		public static ExpertGroup[] GetExpertGroupArray() => new ExpertGroup[]
		{
			new() { Id = 1, Name = "Hi-Fi", },
			new() { Id = 2, Name = "Home Theatre Audio", },
			new() { Id = 3, Name = "Home Theatre Display & Video", },
			new() { Id = 4, Name = "In-car Electronics", },
			new() { Id = 5, Name = "Mobile Devices", },
			new() { Id = 6, Name = "Photography", },
		};

		/// <summary>Returns an array of <see cref="Country"/> objects.</summary>
		/// <returns>An array of <see cref="Country"/> objects.</returns>
		public static Country[] GetCountryArray() => new Country[]
		{
			new() { Id = 1, Name = "Australia", CapitalCity = "Canberra", CallingCode = 61, PPPperCapita = 51885, },
			new() { Id = 2, Name = "Austria", CapitalCity = "Wien", CallingCode = 43, PPPperCapita = 51936, },
			new() { Id = 3, Name = "Belgium", CapitalCity = "Brussels", CallingCode = 32, PPPperCapita = 48224, },
			new() { Id = 4, Name = "Bulgaria", CapitalCity = "Sofia", CallingCode = 359, PPPperCapita = 26034, },
			new() { Id = 5, Name = "Canada", CapitalCity = "Ottawa", CallingCode = 1, PPPperCapita = 52144, },
			new() { Id = 6, Name = "China", CapitalCity = "Beijing", CallingCode = 86, PPPperCapita = 17206, },
			new() { Id = 7, Name = "Croatia", CapitalCity = "Zagreb", CallingCode = 385, PPPperCapita = 29207, },
			new() { Id = 8, Name = "Czech Republic", CapitalCity = "Praha", CallingCode = 420, PPPperCapita = 40585, },
			new() { Id = 9, Name = "Denmark", CapitalCity = "Copenhagen", CallingCode = 45, PPPperCapita = 51643, },
			new() { Id = 10, Name = "Finland", CapitalCity = "Helsinki", CallingCode = 358, PPPperCapita = 49334, },
			new() { Id = 11, Name = "France", CapitalCity = "Paris", CallingCode = 33, PPPperCapita = 45454, },
			new() { Id = 12, Name = "Germany", CapitalCity = "Berlin", CallingCode = 49, PPPperCapita = 53571, },
			new() { Id = 13, Name = "Greece", CapitalCity = "Athens", CallingCode = 30, PPPperCapita = 29045, },
			new() { Id = 14, Name = "Hong Kong", CapitalCity = "Hong Kong", CallingCode = 852, PPPperCapita = 58165, },
			new() { Id = 15, Name = "Hungary", CapitalCity = "Budapest", CallingCode = 36, PPPperCapita = 35941, },
			new() { Id = 16, Name = "India", CapitalCity = "New Delhi", CallingCode = 91, PPPperCapita = 6283, },
			new() { Id = 17, Name = "Italy", CapitalCity = "Roma", CallingCode = 39, PPPperCapita = 40470, },
			new() { Id = 18, Name = "Japan", CapitalCity = "Tokyo", CallingCode = 81, PPPperCapita = 43194, },
			new() { Id = 19, Name = "South Korea", CapitalCity = "Seoul", CallingCode = 82, PPPperCapita = 44292, },
			new() { Id = 20, Name = "Netherlands", CapitalCity = "Amsterdam", CallingCode = 31, PPPperCapita = 58255, },
			new() { Id = 21, Name = "Norway", CapitalCity = "Oslo", CallingCode = 47, PPPperCapita = 79638, },
			new() { Id = 22, Name = "Poland", CapitalCity = "Warszawa", CallingCode = 48, PPPperCapita = 35651, },
			new() { Id = 23, Name = "Portugal", CapitalCity = "Lisboa", CallingCode = 351, PPPperCapita = 36246, },
			new() { Id = 24, Name = "Russia", CapitalCity = "Moscow", CallingCode = 7, PPPperCapita = 28184, },
			new() { Id = 25, Name = "Serbia", CapitalCity = "Belgrade", CallingCode = 381, PPPperCapita = 19767, },
			new() { Id = 26, Name = "Slovakia", CapitalCity = "Bratislava", CallingCode = 421, PPPperCapita = 38321, },
			new() { Id = 27, Name = "Spain", CapitalCity = "Madrid", CallingCode = 34, PPPperCapita = 38143, },
			new() { Id = 28, Name = "Sweden", CapitalCity = "Stockholm", CallingCode = 46, PPPperCapita = 52477, },
			new() { Id = 29, Name = "Switzerland", CapitalCity = "Bern", CallingCode = 41, PPPperCapita = 67557, },
			new() { Id = 30, Name = "Taiwan", CapitalCity = "Taipei", CallingCode = 886, PPPperCapita = 54019, },
			new() { Id = 31, Name = "UK", CapitalCity = "London", CallingCode = 44, PPPperCapita = 46827, },
			new() { Id = 32, Name = "Ukraine", CapitalCity = "Kiev", CallingCode = 380, PPPperCapita = 10310, },
			new() { Id = 33, Name = "USA", CapitalCity = "Washington, D.C.", CallingCode = 1, PPPperCapita = 63051, },
		};

		/// <summary>Returns an array of <see cref="Member"/> objects.</summary>
		/// <returns>An array of <see cref="Member"/> objects.</returns>
		public static Member[] GetMemberArray() => new Member[]
		{
			new() { Id = 1, Name = "Audio", Website = "http://www.audio.com.pl/", ChiefEditor = "Andrzej Kisiel", PhoneNumber = "222 578 430", OfficeLocation = "ul. Leszczynowa 11, 03-197 Warszawa", Publisher = "AVT Corporation", ExpertGroupId = 2, CountryId = 22, },
			new() { Id = 2, Name = "Audio & Cinema em Casa", Website = "http://www.audiopt.com/", ChiefEditor = "Jorge Goncalves", PhoneNumber = "91 723 31 08", OfficeLocation = "Rua Prof. Alfredo de Sousa, 7,  5o. Esq.1600-188 Lisboa", Publisher = "Cadernos do Som Publicacoes", ExpertGroupId = 2, CountryId = 23, },
			new() { Id = 3, Name = "AUDIOverview", Website = "http://www.audioreview.it/", ChiefEditor = "Rocco Patriarca", PhoneNumber = "06 412 182 87", OfficeLocation = "Via Nomentana, 1018  00137 Roma", Publisher = "Audiovideoteam Societa Cooperativa", ExpertGroupId = 2, CountryId = 17, },
			new() { Id = 4, Name = "FWD Magazine", Website = "http://www.fwdmagazine.be/", ChiefEditor = "Jamie Biesemans", PhoneNumber = "473 946983", OfficeLocation = "Van den Hautelei 101,  2100 Deurne", Publisher = "Xingo Invest", ExpertGroupId = 2, CountryId = 3, },
			new() { Id = 5, Name = "Heimkino", Website = "http://www.heimkino-magazin.de/", ChiefEditor = "Michael Voigt", PhoneNumber = "203 42 92 222", OfficeLocation = "Gartroper Strasse 42, D-47138 - Duisburg", Publisher = "Michael E. Brieden Verlag GmbH", ExpertGroupId = 2, CountryId = 12, },
			new() { Id = 6, Name = "HemmaBio", Website = "http://www.hemmabiotidningen.se/", ChiefEditor = "Magnus Fredholm", PhoneNumber = "-(0)733 60 33 88", OfficeLocation = "Vattenverksv?gen 8 - 131 41 Nacka", Publisher = "F?rlaget Hifi & Musik AB", ExpertGroupId = 2, CountryId = 28, },
			new() { Id = 7, Name = "Hi-Files", Website = "http://www.hi-files.com/", ChiefEditor = "Ljubi?a Miodragovi?", PhoneNumber = "63 8866 486", OfficeLocation = "Hektorovi?eva 1B / lokal 6, 11050 Belgrade", Publisher = "Hi-Files Group d.o.o.", ExpertGroupId = 2, CountryId = 25, },
			new() { Id = 8, Name = "Hifimaailma", Website = "http://www.hifimaailma.fi/", ChiefEditor = "Mauri Eronen", PhoneNumber = "4585 65 090", OfficeLocation = "H?meentie 153, - 00560 Helsinki", Publisher = "Fokus Media Finland Oy", ExpertGroupId = 2, CountryId = 10, },
			new() { Id = 9, Name = "Home Cinema Choice", Website = "http://www.homecinemachoice.com/", ChiefEditor = "Mark Craven", PhoneNumber = "1689 869 909", OfficeLocation = "Enterprise House, Enterprise Way, Edenbridge, Kent, TN8 6HF", Publisher = "AVTech Media Ltd", ExpertGroupId = 2, CountryId = 31, },
			new() { Id = 10, Name = "Les Ann?es Laser", Website = "http://www.annees-laser.com/", ChiefEditor = "Gilles Gerin", PhoneNumber = "1 55 25 80 00", OfficeLocation = "20, passage Turquetil, - 75011 Paris", Publisher = "Le 15 du mois SAS", ExpertGroupId = 2, CountryId = 11, },
			new() { Id = 11, Name = "Sound & Vision", Website = "https://www.soundandvision.com/", ChiefEditor = "Al Griffin", PhoneNumber = " ", OfficeLocation = "Madison Avenue, 8 th floor, New York, NY 10016", Publisher = "AVTech Media Ltd", ExpertGroupId = 2, CountryId = 33, },
			new() { Id = 12, Name = "Stereo, Video & Multimedia", Website = "http://stereo-video.kiev.ua/", ChiefEditor = "Julian Zarembovsky", PhoneNumber = "044 223 44 24", OfficeLocation = "Levanevskogo 5, office ?Brand?, 03058 Kiev", Publisher = "Media Most", ExpertGroupId = 2, CountryId = 32, },
			new() { Id = 13, Name = "Sztereó Sound&Vision", Website = "http://www.sztereomagazin.hu/", ChiefEditor = "Rezs? Solt?sz", PhoneNumber = "1 453 1040", OfficeLocation = "Attila út 101, H-1012 Budapest", Publisher = "Solt?sz Rekl?m KFT.", ExpertGroupId = 2, CountryId = 15, },
			new() { Id = 14, Name = "Audio & Cinema em Casa", Website = "http://www.audiopt.com/", ChiefEditor = "Jorge Goncalves", PhoneNumber = "91 723 31 08", OfficeLocation = "Rua Prof. Alfredo de Sousa, 7,  5o. Esq.1600-188 Lisboa", Publisher = "Cadernos do Som Publicacoes", ExpertGroupId = 3, CountryId = 23, },
			new() { Id = 15, Name = "Digital Video HT", Website = "http://www.digitalvideoht.it/", ChiefEditor = "Mario Mollo", PhoneNumber = "06 412 182 87", OfficeLocation = "Via Nomentana, 1018  00137 Roma", Publisher = "Audiovideoteam Societa Cooperativa", ExpertGroupId = 3, CountryId = 17, },
			new() { Id = 16, Name = "FWD Magazine", Website = "http://www.fwdmagazine.be/", ChiefEditor = "Jamie Biesemans", PhoneNumber = "473 946983", OfficeLocation = "Van den Hautelei 101,   2100 Deurne", Publisher = "Xingo Invest", ExpertGroupId = 3, CountryId = 3, },
			new() { Id = 17, Name = "HemmaBio", Website = "http://www.hemmabiotidningen.se/", ChiefEditor = "Magnus Fredholm", PhoneNumber = "(0)733 60 33 88", OfficeLocation = "Vattenverksv?gen 8   131 41 Nacka", Publisher = "F?rlaget Hifi & Musik AB", ExpertGroupId = 3, CountryId = 28, },
			new() { Id = 18, Name = "Hifi Test TV Video", Website = "http://www.hifitest-magazin.de/", ChiefEditor = "Michael Voigt", PhoneNumber = "203 42 92 222", OfficeLocation = "Gartroper Strasse 42, D 47138   Duisburg", Publisher = "Michael E. Brieden Verlag GmbH", ExpertGroupId = 3, CountryId = 12, },
			new() { Id = 19, Name = "Home Cinema Choice", Website = "http://www.homecinemachoice.com/", ChiefEditor = "Mark Craven", PhoneNumber = "1689 869 909", OfficeLocation = "Enterprise House, Enterprise Way, Edenbridge, Kent, TN8 6HF", Publisher = "AVTech Media Ltd", ExpertGroupId = 3, CountryId = 31, },
			new() { Id = 20, Name = "Les Ann?es Laser", Website = "http://www.annees-laser.com/", ChiefEditor = "Gilles Gerin", PhoneNumber = "1 55 25 80 00", OfficeLocation = "20, passage Turquetil, 75011 Paris", Publisher = "Le 15 du mois SAS", ExpertGroupId = 3, CountryId = 11, },
			new() { Id = 21, Name = "ON OFF", Website = "http://www.revistaonoff.es/", ChiefEditor = "Juan Manuel Urraca", PhoneNumber = "670 717 218", OfficeLocation = "Avda. Reyes Cat?licos, 6. Planta 1 3A. 28220 ? Majadahonda, Madrid", Publisher = "TVAV Editorial Multimedia SL", ExpertGroupId = 3, CountryId = 27, },
			new() { Id = 22, Name = "Sound Vision (Hxos)", Website = "http://www.hxoseikona.gr/", ChiefEditor = "Fotios Fotiadis", PhoneNumber = " 211 411 39 58", OfficeLocation = "49, Agisilaou str., 163.46 Hlioupolis", Publisher = "En Sofia Press", ExpertGroupId = 3, CountryId = 13, },
			new() { Id = 23, Name = "Sound+Image", Website = "http://www.avhub.com.au/sound-image", ChiefEditor = "Jez Ford", PhoneNumber = " 2 9160 2135", OfficeLocation = "Suite 3, Level 10, 100 Walker Street, North Sydney, NSW 2060,", Publisher = "Future (Overseas) Limited", ExpertGroupId = 3, CountryId = 1, },
			new() { Id = 24, Name = "Stereo & Video", Website = "http://www.stereovideo.cz/", ChiefEditor = "Lubos Horcic", PhoneNumber = "602 369 369", OfficeLocation = "Th?mova 7, 186 00 Praha 8", Publisher = "Trade & Leisure Publications, spol.s.r.o.", ExpertGroupId = 3, CountryId = 8, },
			new() { Id = 25, Name = "Sztereó Sound&Vision", Website = "http://www.sztereomagazin.hu/", ChiefEditor = "Rezs? Solt?sz", PhoneNumber = "1 453 1040", OfficeLocation = "Attila ?t 101, H-1012 Budapest", Publisher = "Solt?sz Rekl?m KFT.", ExpertGroupId = 3, CountryId = 15, },
			new() { Id = 26, Name = "Audio", Website = "http://www.audio.com.pl/", ChiefEditor = "Andrzej Kisiel", PhoneNumber = "222 578 430", OfficeLocation = "ul. Leszczynowa 11, 03-197 Warszawa", Publisher = "AVT Corporation", ExpertGroupId = 1, CountryId = 22, },
			new() { Id = 27, Name = "Audio & Cinema em Casa", Website = "http://www.audiopt.com/", ChiefEditor = "Jorge Goncalves", PhoneNumber = "91 723 31 08", OfficeLocation = "Rua Prof. Alfredo de Sousa, 7,  5o. Esq.1600-188 Lisboa", Publisher = "Cadernos do Som Publicacoes", ExpertGroupId = 1, CountryId = 23, },
			new() { Id = 28, Name = "Audio Accessory", Website = "https://www.phileweb.com/", ChiefEditor = "Katsunori Isayama", PhoneNumber = "-3-3255-4466", OfficeLocation = "7th AZUMA BLDG, 1-9, Kanda Sakuma-cho, Chiyoda-ku, Tokyo, 101-0025", Publisher = "ONGEN PUBLISHING CO.,LTD.", ExpertGroupId = 1, CountryId = 18, },
			new() { Id = 29, Name = "AUDIOverview", Website = "http://www.audioreview.it/", ChiefEditor = "Rocco Patriarca", PhoneNumber = "06 412 182 87", OfficeLocation = "Via Nomentana, 1018, 00137 Roma", Publisher = "Audiovideoteam Societa Cooperativa", ExpertGroupId = 1, CountryId = 17, },
			new() { Id = 30, Name = "AUDIOTECHNIQUE", Website = "https://www.audiotechnique.com/", ChiefEditor = " ", PhoneNumber = "9611-938", OfficeLocation = "Room 1101, 11 Floor, SUP Tower, No. 75-83 King's Road, North Point", Publisher = " ", ExpertGroupId = 1, CountryId = 14, },
			new() { Id = 31, Name = "Australian Hi-Fi", Website = "http://www.avhub.com.au/hi-fi", ChiefEditor = "Greg Borrowman", PhoneNumber = " 2 9160 2135", OfficeLocation = "Suite 3, Level 10, 100 Walker Street, North Sydney, NSW 2060,", Publisher = "Future (Overseas) Limited", ExpertGroupId = 1, CountryId = 1, },
			new() { Id = 32, Name = "FWD Magazine", Website = "http://www.fwdmagazine.be/", ChiefEditor = "Jamie Biesemans", PhoneNumber = "473 946983", OfficeLocation = "Van den Hautelei 101,  2100 Deurne", Publisher = "Xingo Invest", ExpertGroupId = 1, CountryId = 3, },
			new() { Id = 33, Name = "Hi-Fi News", Website = "http://www.hifinews.co.uk/", ChiefEditor = "Paul Miller", PhoneNumber = "1689 869 909", OfficeLocation = "Enterprise House, Enterprise Way, Edenbridge, Kent, TN8 6HF", Publisher = "AVTech Media Ltd", ExpertGroupId = 1, CountryId = 31, },
			new() { Id = 34, Name = "Hi-Files", Website = "http://www.hi-files.com/", ChiefEditor = "Ljubi?a Miodragovi?", PhoneNumber = "63 8866 486", OfficeLocation = "Hektorovi?eva 1B / lokal 6, 11050 Belgrade", Publisher = "Hi-Files Group d.o.o.", ExpertGroupId = 1, CountryId = 25, },
			new() { Id = 35, Name = "Hifi & Musik", Website = "http://www.hifi-musik.se/", ChiefEditor = "Jonas Bryngelsson", PhoneNumber = "-(0)733 60 33 88", OfficeLocation = "Vattenverksv?gen 8   131 41 Nacka", Publisher = "F?rlaget Hifi & Musik AB", ExpertGroupId = 1, CountryId = 28, },
			new() { Id = 36, Name = "Hifimaailma", Website = "http://www.hifimaailma.fi/", ChiefEditor = "Mauri Eronen", PhoneNumber = "4585 65 090", OfficeLocation = "H?meentie 153, - 00560 Helsinki", Publisher = "Fokus Media Finland Oy", ExpertGroupId = 1, CountryId = 10, },
			new() { Id = 37, Name = "HVT", Website = "http://www.hvt.nl/", ChiefEditor = "Ward Maas", PhoneNumber = "24 76 00 66 0", OfficeLocation = "Kerkenbos 1015E, 6546 BB Nijmegen", Publisher = "Brinkman Media Group BV", ExpertGroupId = 1, CountryId = 20, },
			new() { Id = 38, Name = "Sound Vision (Hxos)", Website = "http://www.hxoseikona.gr/", ChiefEditor = "Fotios Fotiadis", PhoneNumber = " 211 411 39 58", OfficeLocation = "49, Agisilaou str., 163.46 Hlioupolis", Publisher = "En Sofia Press", ExpertGroupId = 1, CountryId = 13, },
			new() { Id = 39, Name = "SOUNDSTAGE! HI-FI", Website = "https://www.soundstagehifi.com/", ChiefEditor = "Doug Schneider", PhoneNumber = "613-297-7651", OfficeLocation = "1953 Meldrum Avenue Ottawa, ON K1J 7V6", Publisher = "c/o Schneider Publishing Inc.", ExpertGroupId = 1, CountryId = 5, },
			new() { Id = 40, Name = "Stereo", Website = "http://www.stereo.de/", ChiefEditor = "Matthias B?de", PhoneNumber = "225 165 04 60", OfficeLocation = "Eifelring 28, D-53879 Euskirchen", Publisher = "R.H. Nitschke Verlag GmbH", ExpertGroupId = 1, CountryId = 12, },
			new() { Id = 41, Name = "Stereo & Video", Website = "http://www.stereovideo.cz/", ChiefEditor = "Lubos Horcic", PhoneNumber = "602 369 369", OfficeLocation = "Th?mova 7, 186 00 Praha 8", Publisher = "Trade & Leisure Publications, spol.s.r.o.", ExpertGroupId = 1, CountryId = 8, },
			new() { Id = 42, Name = "Stereo+", Website = "http://www.stereopluss.no/", ChiefEditor = "Havard Holmedal ", PhoneNumber = "907 43 646", OfficeLocation = "Fridtjof Nansens vei 1E 1472 Fjellhamar", Publisher = "Exciter AS", ExpertGroupId = 1, CountryId = 21, },
			new() { Id = 43, Name = "Stereophile", Website = "https://www.stereophile.com/", ChiefEditor = "Jim Austin", PhoneNumber = " ", OfficeLocation = "Madison Avenue, 8 th floor, New York, NY 10016", Publisher = "AVTech Media Ltd", ExpertGroupId = 1, CountryId = 33, },
			new() { Id = 44, Name = "Sztereó Sound&Vision", Website = "http://www.sztereomagazin.hu/", ChiefEditor = "Rezs? Solt?sz", PhoneNumber = "1 453 1040", OfficeLocation = "Attila ?t 101, H-1012 Budapest", Publisher = "Solt?sz Rekl?m KFT.", ExpertGroupId = 1, CountryId = 15, },
			new() { Id = 45, Name = "12 Voltios Car Audio & Technology", Website = "http://www.12vpersonalcar.com/", ChiefEditor = "Edgar Compte", PhoneNumber = " 934 238 404", OfficeLocation = "C/Tarragona 84-90, 1?-8?, 08015 Barcelona", Publisher = "Ideas Editoriales 3003 SL", ExpertGroupId = 4, CountryId = 27, },
			new() { Id = 46, Name = "A3/AvtoZvuk", Website = "http://xn--80aeatqv1al.xn--p1ai/", ChiefEditor = "Anatoly Shikhatov", PhoneNumber = "495 788 05 44", OfficeLocation = "Rumyantsevo business park, block D, office 841, Moscow", Publisher = "Anatoly Shikhatov", ExpertGroupId = 4, CountryId = 24, },
			new() { Id = 47, Name = "ACS AudioCarStereo", Website = "http://www.audiocarstereo.it/", ChiefEditor = "Rocco Patriarca", PhoneNumber = "06 412 182 87", OfficeLocation = "Via Nomentana, 1018  00137 Roma", Publisher = "Audiovideoteam Societa Cooperativa", ExpertGroupId = 4, CountryId = 17, },
			new() { Id = 48, Name = "Australian InCar", Website = "http://www.avhub.com.au/incar", ChiefEditor = "Jez Ford", PhoneNumber = " 2 9901 6100", OfficeLocation = "Level 6, Building A, 207 Pacific Highway, St Leonards, NSW 2065,", Publisher = "nextmedia pty ltd", ExpertGroupId = 4, CountryId = 1, },
			new() { Id = 49, Name = "AutoSound Technical Magazine", Website = "http://www.autosound.fi/", ChiefEditor = "Teppo Hirvikunnas", PhoneNumber = "810 778 64 01", OfficeLocation = "Teerlakiantie 262, 21530 PAIMIO", Publisher = "JTS-Media", ExpertGroupId = 4, CountryId = 10, },
			new() { Id = 50, Name = "Car&Hifi", Website = "http://www.carhifi-magazin.de/", ChiefEditor = "Elmar Michels", PhoneNumber = "203 42 92 222", OfficeLocation = "Gartroper Strasse 42, D 47138   Duisburg", Publisher = "Michael E. Brieden Verlag GmbH", ExpertGroupId = 4, CountryId = 12, },
			new() { Id = 51, Name = "Stereo, Video & Multimedia", Website = "http://stereo-video.kiev.ua/", ChiefEditor = "Julian Zarembovsky", PhoneNumber = "044 223 44 24", OfficeLocation = "Levanevskogo 5, office ?Brand?, 03058 Kiev", Publisher = "Media Most", ExpertGroupId = 4, CountryId = 32, },
			new() { Id = 52, Name = "AV Magazine", Website = "https://www.avmagazine.it/", ChiefEditor = "Emidio Frattaroli", PhoneNumber = "393 9013731", OfficeLocation = "via G. Cameli 21, 64100 Teramo (TE)", Publisher = "AV Raw S.n.c.", ExpertGroupId = 5, CountryId = 17, },
			new() { Id = 53, Name = "Bug", Website = "http://www.bug.hr/", ChiefEditor = "Dragan Petric", PhoneNumber = "513 821 555", OfficeLocation = "Ogrizoviceva 36A, HR-1000, Zagreb", Publisher = "Bug d.o.o.", ExpertGroupId = 5, CountryId = 7, },
			new() { Id = 54, Name = "Computer!Totaal", Website = "https://computertotaal.nl/", ChiefEditor = "Jeroen de Jager", PhoneNumber = "235 430 000", OfficeLocation = "Richard Holkade 8, NL-2033 PZ Haarlem", Publisher = "Reshift Digital", ExpertGroupId = 5, CountryId = 20, },
			new() { Id = 55, Name = "Datatid TechLife", Website = "http://www.datatid.dk/", ChiefEditor = "Knud Sondergaard", PhoneNumber = "221 199 40", OfficeLocation = "Lautrupsgade 7, DK-2100 Copenhagen O", Publisher = "Audio Media A/S", ExpertGroupId = 5, CountryId = 9, },
			new() { Id = 56, Name = "Hi-Files", Website = "http://www.hi-files.com/", ChiefEditor = "Ljubi?a Miodragovi?", PhoneNumber = "63 8866 486", OfficeLocation = "Hektorovi?eva 1B / lokal 6, 11050 Belgrade", Publisher = "Hi-Files Group d.o.o.", ExpertGroupId = 5, CountryId = 25, },
			new() { Id = 57, Name = "HiComm", Website = "http://www.hicomm.bg/", ChiefEditor = "Yoana Andreeva", PhoneNumber = "88 8818887", OfficeLocation = "145B, Rakovski Blvd., 1000, Sofia", Publisher = "HiEnd Publishing", ExpertGroupId = 5, CountryId = 4, },
			new() { Id = 58, Name = "ON OFF", Website = "http://www.revistaonoff.es/", ChiefEditor = "Juan Manuel Urraca", PhoneNumber = "670 717 218", OfficeLocation = "Avda. Reyes Cat?licos, 6. Planta 1 3A. 28220 ? Majadahonda, Madrid", Publisher = "TVAV Editorial Multimedia SL", ExpertGroupId = 5, CountryId = 27, },
			new() { Id = 59, Name = "Sound Vision (Hxos)", Website = "http://www.hxoseikona.gr/", ChiefEditor = "Fotios Fotiadis", PhoneNumber = " 211 411 39 58", OfficeLocation = "49, Agisilaou str., 163.46 Hlioupolis", Publisher = "En Sofia Press", ExpertGroupId = 5, CountryId = 13, },
			new() { Id = 60, Name = "Stereo & Video", Website = "http://www.stereovideo.cz/", ChiefEditor = "Lubos Horcic", PhoneNumber = "602 369 369", OfficeLocation = "Th?mova 7, 186 00 Praha 8", Publisher = "Trade & Leisure Publications, spol.s.r.o.", ExpertGroupId = 5, CountryId = 8, },
			new() { Id = 61, Name = "touchIT", Website = "https://touchit.sk/", ChiefEditor = "Ondrej Macko", PhoneNumber = "19 11 04 60 06", OfficeLocation = "Reding Tower 2, Ra?ianska 153, 831 54 Bratislava ? Ra?a", Publisher = "ASTON ITM", ExpertGroupId = 5, CountryId = 26, },
		};

		/// <summary>Returns an array of <see cref="Brand"/> objects.</summary>
		/// <returns>An array of <see cref="Brand"/> objects.</returns>
		public static Brand[] GetBrandArray() => new Brand[]
		{
			new() { Id = 1, Name = "Arcam", Homepage = "https://www.arcam.co.uk/", Address = "Waterbeach, Cambridge", CountryId = 31, },
			new() { Id = 2, Name = "Arendal Sound", Homepage = "https://arendalsound.eu/", Address = "Arendal", CountryId = 21, },
			new() { Id = 3, Name = "AudioQuest", Homepage = "https://www.audioquest.com/", Address = "Irvine, CA", CountryId = 33, },
			new() { Id = 4, Name = "Audison", Homepage = "https://www.audison.eu/", Address = "Marignano MC", CountryId = 17, },
			new() { Id = 5, Name = "Bang & Olufsen", Homepage = "https://www.bang-olufsen.com/en", Address = "Struer", CountryId = 9, },
			new() { Id = 6, Name = "Bowers & Wilkins", Homepage = "https://www.bowerswilkins.com/net", Address = "West Sussex", CountryId = 31, },
			new() { Id = 7, Name = "Canon", Homepage = "https://global.canon/en/", Address = "Ota City, Tokyo", CountryId = 18, },
			new() { Id = 8, Name = "DALI", Homepage = "https://www.dali-speakers.com", Address = "Norager", CountryId = 9, },
			new() { Id = 9, Name = "Denon", Homepage = "https://www.denon.com", Address = " ", CountryId = 18, },
			new() { Id = 10, Name = "DJI", Homepage = "https://www.dji.com/", Address = "Nanshan District, Shenzhen", CountryId = 6, },
			new() { Id = 11, Name = "DxO Labs", Homepage = "https://www.dxo.com/", Address = "Paris", CountryId = 11, },
			new() { Id = 12, Name = "EIZO", Homepage = "https://www.eizoglobal.com/", Address = "Hakusan, Ishikawa", CountryId = 18, },
			new() { Id = 13, Name = "Emotiva", Homepage = "https://emotiva.com/", Address = "Franklin, Williamson County, Tennessee", CountryId = 33, },
			new() { Id = 14, Name = "ESB", Homepage = "https://www.esbcar.com/", Address = "Via della Meccanica, 14, 04011 Aprilia (Latina)", CountryId = 17, },
			new() { Id = 15, Name = "ETON", Homepage = "https://www.eton-gmbh.com/en/", Address = "Pfaffenweg 21, 89231 Neu-Ulm", CountryId = 12, },
			new() { Id = 16, Name = "FiiO", Homepage = "https://www.fiio.com/", Address = "Guangzhou", CountryId = 6, },
			new() { Id = 17, Name = "Focal", Homepage = "https://www.focal.com/en", Address = "Paris", CountryId = 11, },
			new() { Id = 18, Name = "Fujifilm", Homepage = "https://www.fujifilm.com/", Address = "Minato, Tokyo", CountryId = 18, },
			new() { Id = 19, Name = "Ground Zero", Homepage = "https://groundzerousa.com/", Address = "Erlenweg 25, 85658 Egmating", CountryId = 12, },
			new() { Id = 20, Name = "Harman-Kardon", Homepage = "https://eu.harmankardon.com/", Address = "Stamford, Connecticut", CountryId = 33, },
			new() { Id = 21, Name = "Audiotec Fischer", Homepage = "https://www.audiotec-fischer.de/en", Address = "H?negr?ben 26, 57392 Schmallenberg", CountryId = 12, },
			new() { Id = 22, Name = "Hifonics", Homepage = "https://hifonics.com/", Address = "851 E. Park Ave, Libertyville, IL", CountryId = 33, },
			new() { Id = 23, Name = "Huawei", Homepage = "https://www.huawei.com/en/", Address = "Shenzhen", CountryId = 6, },
			new() { Id = 24, Name = "iFi Audio", Homepage = "https://ifi-audio.com/home", Address = "79 Scarisbrick New Road, Southport", CountryId = 31, },
			new() { Id = 25, Name = "JVC", Homepage = "https://www.jvc.net/", Address = "Kenagawa Ward, Yokohama, Kanagawa", CountryId = 18, },
			new() { Id = 26, Name = "Kenwood", Homepage = "https://www.kenwood.com/", Address = "Hachioji-shi, Tokyo", CountryId = 18, },
			new() { Id = 27, Name = "LG", Homepage = "https://www.lg.com/global", Address = "Seoul", CountryId = 19, },
			new() { Id = 28, Name = "Monitor Audio", Homepage = "https://www.monitoraudio.com/", Address = "Cambridge, England", CountryId = 31, },
			new() { Id = 29, Name = "Mosconi", Homepage = "https://mosconi-system.it/", Address = "Via La Villa, 28, Ghilardino di Fossombrone", CountryId = 17, },
			new() { Id = 30, Name = "Musical Fidelity", Homepage = "https://www.musicalfidelity.com/", Address = "Margaretenstrasse 98, A-1050 Wien", CountryId = 31, },
			new() { Id = 31, Name = "NAD", Homepage = "https://nadelectronics.com/", Address = "Pickering", CountryId = 5, },
			new() { Id = 32, Name = "Nikon", Homepage = "https://www.nikon.com/", Address = "Tokyo", CountryId = 18, },
			new() { Id = 33, Name = "OnePlus", Homepage = "https://www.oneplus.com/", Address = "Futian district, Shenzhen", CountryId = 6, },
			new() { Id = 34, Name = "OPPO", Homepage = "https://www.oppo.com/en/", Address = "Dongguan, Guangdong", CountryId = 6, },
			new() { Id = 35, Name = "Optoma", Homepage = "https://www.optomaeurope.com/", Address = "New Taipei City", CountryId = 30, },
			new() { Id = 36, Name = "Philips", Homepage = "https://www.philips.com/global", Address = "Amsterdam", CountryId = 20, },
			new() { Id = 37, Name = "Primare", Homepage = "https://primare.net/", Address = "Limstensgatan 7, SE-216 16 Limhamn", CountryId = 28, },
			new() { Id = 38, Name = "Pro-Ject", Homepage = "https://www.project-audio.com/en/", Address = "Analogweg 1, A-2130 Mistelbach", CountryId = 2, },
			new() { Id = 39, Name = "ROTEL Michi", Homepage = "http://www.rotel.com/en-gb/michi", Address = "Dale Road, Worthing, West Sussex", CountryId = 31, },
			new() { Id = 40, Name = "Samsung", Homepage = "https://www.samsung.com/", Address = "Seoul", CountryId = 19, },
			new() { Id = 41, Name = "Sennheiser", Homepage = "https://en-uk.sennheiser.com/", Address = "Am Labor 1, DE-30900 Wedemark", CountryId = 12, },
			new() { Id = 42, Name = "Sony", Homepage = "https://www.sony.net/", Address = "Sony City, Minato, Tokyo?", CountryId = 18, },
			new() { Id = 43, Name = "SVS", Homepage = "https://www.svsound.com/", Address = "Youngstown (Ohio state)", CountryId = 33, },
			new() { Id = 44, Name = "System Audio", Homepage = "https://system-audio.com/", Address = "Klosterengen 137 L, 4000 Roskilde.", CountryId = 9, },
			new() { Id = 45, Name = "TCL", Homepage = "https://www.tcl.com/", Address = "Huizhou, Guangdong", CountryId = 6, },
			new() { Id = 46, Name = "Thorens", Homepage = "https://thorens.com/", Address = "Lustheide 85, 51427 Bergisch Gladbach", CountryId = 12, },
			new() { Id = 47, Name = "Triangle", Homepage = "https://www.trianglehifi.com/en/", Address = "Villeneuve Saint Germain", CountryId = 11, },
			new() { Id = 48, Name = "Trinnov", Homepage = "https://www.trinnov.com/", Address = "5 rue Edmond Michelet, 93360 Neuilly-Plaisance", CountryId = 11, },
			new() { Id = 49, Name = "Volumio", Homepage = "https://volumio.org/", Address = "Firenze", CountryId = 17, },
			new() { Id = 50, Name = "Zappiti", Homepage = "https://www.zappiti.com/", Address = "Paris", CountryId = 11, },
			new() { Id = 51, Name = "Zenec", Homepage = "http://www.zenec.com/", Address = "Bohrturmweg 1, 5330 Bad Zurzach", CountryId = 29, },
		};

		/// <summary>Returns an array of <see cref="Product"/> objects.</summary>
		/// <returns>An array of <see cref="Product"/> objects.</returns>
		public static Product[] GetProductArray() => new Product[]
		{
			new() { Id = 1, Name = "Chora 826", Category = "BEST VALUE FLOORSTANDING LOUDSPEAKER", Price = 297730, LaunchDate = new System.DateTime(2021, 7, 7), EstimatedLifetime = 2, BrandId = 17, ExpertGroupId = 1, },
			new() { Id = 2, Name = "Prime Pinnacle", Category = "BEST LOUDSPEAKER ", Price = 554706, LaunchDate = new System.DateTime(2021, 7, 8), EstimatedLifetime = 4, BrandId = 43, ExpertGroupId = 1, },
			new() { Id = 3, Name = "Bronze 100", Category = "BEST VALUE BOOKSHELF LOUDSPEAKER", Price = 247403, LaunchDate = new System.DateTime(2021, 6, 9), EstimatedLifetime = 3, BrandId = 28, ExpertGroupId = 1, },
			new() { Id = 4, Name = "Legend 5 silverback", Category = "BEST WIRELESS LOUDSPEAKER", Price = 540393, LaunchDate = new System.DateTime(2021, 8, 12), EstimatedLifetime = 4, BrandId = 44, ExpertGroupId = 1, },
			new() { Id = 5, Name = "Masters M33", Category = "BEST SMART AMPLIFIER", Price = 493561, LaunchDate = new System.DateTime(2021, 8, 4), EstimatedLifetime = 7, BrandId = 31, ExpertGroupId = 1, },
			new() { Id = 6, Name = "SA30", Category = "BEST AMPLIFIER", Price = 829407, LaunchDate = new System.DateTime(2021, 6, 21), EstimatedLifetime = 4, BrandId = 1, ExpertGroupId = 1, },
			new() { Id = 7, Name = "M8xi", Category = "BEST HIGH-END INTEGRATED AMPLIFIER", Price = 376669, LaunchDate = new System.DateTime(2021, 7, 19), EstimatedLifetime = 5, BrandId = 30, ExpertGroupId = 1, },
			new() { Id = 8, Name = "P5/S5", Category = "HIGH-END PRE/POWER AMPLIFIER", Price = 666753, LaunchDate = new System.DateTime(2021, 8, 21), EstimatedLifetime = 5, BrandId = 39, ExpertGroupId = 1, },
			new() { Id = 9, Name = "TD 1601", Category = "BEST TURNTABLE", Price = 376466, LaunchDate = new System.DateTime(2021, 7, 9), EstimatedLifetime = 5, BrandId = 46, ExpertGroupId = 1, },
			new() { Id = 10, Name = "T1", Category = "BEST VALUE TURNTABLE", Price = 750613, LaunchDate = new System.DateTime(2021, 6, 23), EstimatedLifetime = 7, BrandId = 38, ExpertGroupId = 1, },
			new() { Id = 11, Name = "ZEN DAC", Category = "BEST VALUE DAC", Price = 667973, LaunchDate = new System.DateTime(2021, 7, 8), EstimatedLifetime = 1, BrandId = 24, ExpertGroupId = 1, },
			new() { Id = 12, Name = "Primo", Category = "BEST DIGITAL SOURCE", Price = 972976, LaunchDate = new System.DateTime(2021, 7, 5), EstimatedLifetime = 0, BrandId = 49, ExpertGroupId = 1, },
			new() { Id = 13, Name = "VC-E", Category = "BEST AUDIO ACCESSORY", Price = 702675, LaunchDate = new System.DateTime(2021, 7, 16), EstimatedLifetime = 0, BrandId = 38, ExpertGroupId = 1, },
			new() { Id = 14, Name = "R15", Category = "BEST PHONO PREAMP", Price = 640462, LaunchDate = new System.DateTime(2021, 6, 22), EstimatedLifetime = 6, BrandId = 37, ExpertGroupId = 1, },
			new() { Id = 15, Name = "M11 Pro", Category = "BEST MOBILE AUDIO PLAYER", Price = 527486, LaunchDate = new System.DateTime(2021, 8, 9), EstimatedLifetime = 3, BrandId = 16, ExpertGroupId = 1, },
			new() { Id = 16, Name = "IO-6", Category = "BEST HEADPHONES", Price = 180529, LaunchDate = new System.DateTime(2021, 7, 4), EstimatedLifetime = 4, BrandId = 8, ExpertGroupId = 1, },
			new() { Id = 17, Name = "DragonFly Cobalt", Category = "PORTABLE DAC/HEADPHONE AMPLIFIER", Price = 380919, LaunchDate = new System.DateTime(2021, 6, 10), EstimatedLifetime = 8, BrandId = 3, ExpertGroupId = 1, },
			new() { Id = 18, Name = "1961 Series", Category = "HOME THEATRE SPEAKER SYSTEM", Price = 100835, LaunchDate = new System.DateTime(2021, 7, 21), EstimatedLifetime = 0, BrandId = 2, ExpertGroupId = 2, },
			new() { Id = 19, Name = "Borea Series", Category = "BEST BUY HOME THEATRE SPEAKER SYSTEM", Price = 589328, LaunchDate = new System.DateTime(2021, 6, 26), EstimatedLifetime = 4, BrandId = 47, ExpertGroupId = 2, },
			new() { Id = 20, Name = "SN8YG", Category = "BEST SOUNDBAR", Price = 677979, LaunchDate = new System.DateTime(2021, 8, 6), EstimatedLifetime = 0, BrandId = 27, ExpertGroupId = 2, },
			new() { Id = 21, Name = "Beosound Stage", Category = "BEST PREMIUM SOUNDBAR", Price = 859550, LaunchDate = new System.DateTime(2021, 7, 9), EstimatedLifetime = 1, BrandId = 5, ExpertGroupId = 2, },
			new() { Id = 22, Name = "Citation MultiBeam 700", Category = "Best SMART SOUNDBAR", Price = 575493, LaunchDate = new System.DateTime(2021, 6, 4), EstimatedLifetime = 5, BrandId = 20, ExpertGroupId = 2, },
			new() { Id = 23, Name = "TS9030 RAY?DANZ", Category = "Best Buy Soundbar", Price = 239516, LaunchDate = new System.DateTime(2021, 7, 7), EstimatedLifetime = 6, BrandId = 45, ExpertGroupId = 2, },
			new() { Id = 24, Name = "AVC-X4700H", Category = "BEST HOME THEATRE RECEIVER", Price = 810833, LaunchDate = new System.DateTime(2021, 8, 11), EstimatedLifetime = 2, BrandId = 9, ExpertGroupId = 2, },
			new() { Id = 25, Name = "Altitude platform", Category = "High-End Home Theatre", Price = 386734, LaunchDate = new System.DateTime(2021, 6, 17), EstimatedLifetime = 6, BrandId = 48, ExpertGroupId = 2, },
			new() { Id = 26, Name = "XPA Gen3", Category = "BEST HOME THEATRE RECEIVER", Price = 847201, LaunchDate = new System.DateTime(2021, 8, 10), EstimatedLifetime = 7, BrandId = 13, ExpertGroupId = 2, },
			new() { Id = 27, Name = "EXOFIELD XP-EXT1", Category = "BEST HOME THEATRE HEADPHONE", Price = 213521, LaunchDate = new System.DateTime(2021, 8, 4), EstimatedLifetime = 8, BrandId = 25, ExpertGroupId = 2, },
			new() { Id = 28, Name = "SB-2000 Pro", Category = "BEST HOME THEATRE SUBWOOFER", Price = 192471, LaunchDate = new System.DateTime(2021, 7, 20), EstimatedLifetime = 7, BrandId = 43, ExpertGroupId = 2, },
			new() { Id = 29, Name = "Pro 4K HDR", Category = "Best Home Theatre Media Player", Price = 941071, LaunchDate = new System.DateTime(2021, 7, 1), EstimatedLifetime = 1, BrandId = 50, ExpertGroupId = 2, },
			new() { Id = 30, Name = "OLED65GX", Category = "BEST PREMIUM OLED TV", Price = 155502, LaunchDate = new System.DateTime(2021, 7, 18), EstimatedLifetime = 8, BrandId = 27, ExpertGroupId = 3, },
			new() { Id = 31, Name = "75NANO99", Category = "BEST 8K TV", Price = 522565, LaunchDate = new System.DateTime(2021, 8, 20), EstimatedLifetime = 2, BrandId = 27, ExpertGroupId = 3, },
			new() { Id = 32, Name = "QE75Q950TS", Category = "BEST LARGE SCREEN TV", Price = 103927, LaunchDate = new System.DateTime(2021, 6, 13), EstimatedLifetime = 1, BrandId = 40, ExpertGroupId = 3, },
			new() { Id = 33, Name = "55OLED805", Category = "BEST BUY OLED TV", Price = 563701, LaunchDate = new System.DateTime(2021, 5, 28), EstimatedLifetime = 2, BrandId = 36, ExpertGroupId = 3, },
			new() { Id = 34, Name = "65OLED935", Category = "BEST HOME THEATRE TV", Price = 810888, LaunchDate = new System.DateTime(2021, 5, 29), EstimatedLifetime = 0, BrandId = 36, ExpertGroupId = 3, },
			new() { Id = 35, Name = "65C815", Category = "BEST BUY TV", Price = 788144, LaunchDate = new System.DateTime(2021, 7, 2), EstimatedLifetime = 6, BrandId = 45, ExpertGroupId = 3, },
			new() { Id = 36, Name = "CinemaX UHZ65UST", Category = "BEST PROJECTOR", Price = 664300, LaunchDate = new System.DateTime(2021, 6, 19), EstimatedLifetime = 5, BrandId = 35, ExpertGroupId = 3, },
			new() { Id = 37, Name = "DMX9720XDS", Category = "BEST IN-CAR HEAD UNIT", Price = 369823, LaunchDate = new System.DateTime(2021, 6, 16), EstimatedLifetime = 4, BrandId = 26, ExpertGroupId = 4, },
			new() { Id = 38, Name = "Helix DSP ULTRA", Category = "BEST IN-CAR SOUND PROCESSOR", Price = 630222, LaunchDate = new System.DateTime(2021, 7, 11), EstimatedLifetime = 8, BrandId = 21, ExpertGroupId = 4, },
			new() { Id = 39, Name = "GZDSP 4-8XII", Category = "BEST VALUE IN-CAR DSP", Price = 72726, LaunchDate = new System.DateTime(2021, 6, 22), EstimatedLifetime = 1, BrandId = 19, ExpertGroupId = 4, },
			new() { Id = 40, Name = "GLADEN ATOMO 2", Category = "BEST IN-CAR AMPLIFIER", Price = 303415, LaunchDate = new System.DateTime(2021, 6, 26), EstimatedLifetime = 2, BrandId = 29, ExpertGroupId = 4, },
			new() { Id = 41, Name = "Stealth 7.1 DSP", Category = "BEST IN-CAR DSP AMPLIFIER", Price = 483518, LaunchDate = new System.DateTime(2021, 8, 15), EstimatedLifetime = 1, BrandId = 15, ExpertGroupId = 4, },
			new() { Id = 42, Name = "8.6K3U LE", Category = "BEST IN-CAR SPEAKER SYSTEM", Price = 770384, LaunchDate = new System.DateTime(2021, 7, 27), EstimatedLifetime = 0, BrandId = 14, ExpertGroupId = 4, },
			new() { Id = 43, Name = "ZRX6D2", Category = "BEST IN-CAR SUBWOOFER", Price = 42560, LaunchDate = new System.DateTime(2021, 7, 28), EstimatedLifetime = 8, BrandId = 22, ExpertGroupId = 4, },
			new() { Id = 44, Name = "DRV-A501W", Category = "BEST IN-CAR DASHCAM", Price = 521829, LaunchDate = new System.DateTime(2021, 7, 27), EstimatedLifetime = 1, BrandId = 26, ExpertGroupId = 4, },
			new() { Id = 45, Name = "bit One HD Virtuoso", Category = "BEST IN-CAR HIGH END COMPONENT", Price = 592232, LaunchDate = new System.DateTime(2021, 7, 17), EstimatedLifetime = 2, BrandId = 4, ExpertGroupId = 4, },
			new() { Id = 46, Name = "Z-E3766", Category = "BEST CAMPERVAN HEAD UNIT", Price = 910550, LaunchDate = new System.DateTime(2021, 7, 17), EstimatedLifetime = 7, BrandId = 51, ExpertGroupId = 4, },
			new() { Id = 47, Name = "8 Pro", Category = "BEST SMARTPHONE", Price = 188835, LaunchDate = new System.DateTime(2021, 7, 28), EstimatedLifetime = 7, BrandId = 33, ExpertGroupId = 5, },
			new() { Id = 48, Name = "Find X2 Pro", Category = "BEST ADVANCED SMARTPHONE", Price = 527684, LaunchDate = new System.DateTime(2021, 6, 12), EstimatedLifetime = 5, BrandId = 34, ExpertGroupId = 5, },
			new() { Id = 49, Name = "P40 Pro", Category = "BEST SMARTPHONE CAMERA", Price = 424986, LaunchDate = new System.DateTime(2021, 6, 2), EstimatedLifetime = 5, BrandId = 23, ExpertGroupId = 5, },
			new() { Id = 50, Name = "Galaxy Z Flip", Category = "BEST FOLDABLE SMARTPHONE", Price = 261694, LaunchDate = new System.DateTime(2021, 8, 20), EstimatedLifetime = 0, BrandId = 40, ExpertGroupId = 5, },
			new() { Id = 51, Name = "Xperia 1 II", Category = "BEST MULTIMEDIA SMARTPHONE", Price = 77971, LaunchDate = new System.DateTime(2021, 7, 30), EstimatedLifetime = 2, BrandId = 42, ExpertGroupId = 5, },
			new() { Id = 52, Name = "PX5", Category = "BEST ON-EAR HEADPHONES", Price = 982684, LaunchDate = new System.DateTime(2021, 7, 23), EstimatedLifetime = 7, BrandId = 6, ExpertGroupId = 5, },
			new() { Id = 53, Name = "IO-6", Category = "BEST HEADPHONES", Price = 906359, LaunchDate = new System.DateTime(2021, 8, 21), EstimatedLifetime = 2, BrandId = 8, ExpertGroupId = 5, },
			new() { Id = 54, Name = "Momentum True Wireless 2", Category = "BEST IN-EAR HEADPHONES", Price = 580143, LaunchDate = new System.DateTime(2021, 6, 26), EstimatedLifetime = 3, BrandId = 41, ExpertGroupId = 5, },
			new() { Id = 55, Name = "Watch GT 2", Category = "BEST SMARTWATCH", Price = 668565, LaunchDate = new System.DateTime(2021, 6, 6), EstimatedLifetime = 4, BrandId = 23, ExpertGroupId = 5, },
			new() { Id = 56, Name = "M11 Pro", Category = "BEST MOBILE AUDIO PLAYER", Price = 304437, LaunchDate = new System.DateTime(2021, 8, 19), EstimatedLifetime = 0, BrandId = 16, ExpertGroupId = 5, },
			new() { Id = 57, Name = "XBOOM Go PL7", Category = "BEST MOBILE SPEAKER", Price = 727376, LaunchDate = new System.DateTime(2021, 8, 9), EstimatedLifetime = 2, BrandId = 27, ExpertGroupId = 5, },
			new() { Id = 58, Name = "X-T4", Category = "EISA CAMERA OF THE YEAR", Price = 317487, LaunchDate = new System.DateTime(2021, 8, 12), EstimatedLifetime = 3, BrandId = 18, ExpertGroupId = 6, },
			new() { Id = 59, Name = "Z 50", Category = "BEST BUY CAMERA", Price = 442246, LaunchDate = new System.DateTime(2021, 5, 28), EstimatedLifetime = 2, BrandId = 32, ExpertGroupId = 6, },
			new() { Id = 60, Name = "D780", Category = "BEST FULL-FRAME CAMERA", Price = 485417, LaunchDate = new System.DateTime(2021, 7, 22), EstimatedLifetime = 3, BrandId = 32, ExpertGroupId = 6, },
			new() { Id = 61, Name = "EOS-1D X Mark III", Category = "BEST PROFESSIONAL CAMERA", Price = 551797, LaunchDate = new System.DateTime(2021, 6, 13), EstimatedLifetime = 2, BrandId = 7, ExpertGroupId = 6, },
			new() { Id = 62, Name = "X100V", Category = "BEST COMPACT CAMERA", Price = 851462, LaunchDate = new System.DateTime(2021, 7, 13), EstimatedLifetime = 0, BrandId = 18, ExpertGroupId = 6, },
			new() { Id = 63, Name = "Vlog Camera ZV-1", Category = "Best Vlogging Camera", Price = 869702, LaunchDate = new System.DateTime(2021, 6, 28), EstimatedLifetime = 0, BrandId = 42, ExpertGroupId = 6, },
			new() { Id = 64, Name = "EOS R5", Category = "BEST CAMERA INNOVATION", Price = 407926, LaunchDate = new System.DateTime(2021, 8, 22), EstimatedLifetime = 3, BrandId = 7, ExpertGroupId = 6, },
			new() { Id = 65, Name = "Mavic Air 2", Category = "BEST CAMERA DRONE", Price = 537790, LaunchDate = new System.DateTime(2021, 6, 28), EstimatedLifetime = 5, BrandId = 10, ExpertGroupId = 6, },
			new() { Id = 66, Name = "Nik Collection 3", Category = "BEST PHOTO SOFTWARE", Price = 441740, LaunchDate = new System.DateTime(2021, 6, 5), EstimatedLifetime = 8, BrandId = 11, ExpertGroupId = 6, },
			new() { Id = 67, Name = "ColorEdge CS2740", Category = "MONITOR OF THE YEAR", Price = 202890, LaunchDate = new System.DateTime(2021, 8, 11), EstimatedLifetime = 7, BrandId = 12, ExpertGroupId = 6, },
		};
	}
}
